#!/bin/bash

usage() {
  echo "Usage: $0 <command> [options]"
  echo ""
  echo "Commands:"
  echo "  rep-cluster     Run get_rep_cluster_genomes_info.py"
  echo ""
  echo "Use '$0 <command> --help' to see the options for a specific command."
  exit 1
}


if [ "$#" -lt 1 ]; then
  echo "Error: No command specified."
  usage
fi


command=$1
shift

script_path=$(readlink -f $0)
script_dir=$(dirname $script_path)

case $command in
  rep-cluster)
    python $script_dir/get_rep_cluster_genomes_info.py "$@"
    ;;
  *)
    echo "Error: Unknown command '$command'."
    usage
    ;;
esac
