#!/bin/bash

set -e
function print_help() {
  echo "Usage: $0 -f genomes_info -s/-l -r read.fq [option]"
  echo "       paired-end: $0 -f genomes_info -s -p -r read.fq --species-level"
  echo ""
  echo "Strain-level taxonomic classification of metagenomic data using pangenome graphs"
  echo ""
  echo "Author: Weihai Zhang"
  echo "Date:   May 2024"
  echo ""
  echo "    General options:"
  echo "        --create                          Create database only."
  echo "        --vg FILE                         Path to vg executable file."
  echo "        -n, --next                        Keep the temporary folder for later use at the strain level." 
  echo "        --debug                           Keep the temporary folder for any situation."
  echo "        --sample                          Sampling nodes(500) are used for small model testing (set for codeocean)."
  echo "        -v, --verbose                     Detailed database build log."
  echo "        -t, --threads INT                 Number of processes to run in parallel(default: 64)."
  echo "        --help, -h                        Print this help message."
  echo "        --version                         Print the version info."
  echo "    Database creation:"
  echo "        -f, --genomesInformation FILE:    A list of reference genomes in specified format (Mandatory)."
  echo "        -db NAME                          Name for pantax DB (default: pantax_db)."
  echo "    Index construction:"
  echo "        -s, --short-read                  Short read alignment."
  echo "        --best                            Best autoindex(only used with -s)."
  echo "        -l, --long-read                   Long read alignment."
  echo "        --fast                            Fast index(only used with -l)."
  echo "    Read classification:"
  echo "        -r, --fastq-in FILE               Read and align FASTQ-format reads from FILE (two are allowed with -p)."
  echo "        -p, --paired                      For paired-end alignment."
  echo "    Abundacnce calculation:"
  echo "        --species-level                   Species abundance calulation."
  echo "        --strain-level                    Strain abundance calulation."
  echo "        -a float                          Species with more than abundance threshold used for strain abundance calulation.(default: 0.0001)."
  echo "        -fr float                         Unique trio nodes fraction(default: 0.3)."
  echo "        -fc float                         Unique trio nodes mean count fraction(default: 0.45)."
  echo "        --filter                          MAPQ-based filter."
  echo "        --min_cov int                     Minimum coverage required per strain(default: 0)."
  echo "        --min_depth int                   Graph nodes with sequence depth less than <min_depth>(default: 0)."
  echo "        -gt int                           Gurobi threads(default: 1)."
  echo "        -g, --save                        Save species graph information."
  echo "        -S, --classified-out FILENAME     File for alignment output(prefix)."
  echo "        -R, --report FILENAME             File for read classification output(prefix)."
  echo "        -o, --ouput FILENAME              File for abundance output(prefix)."
  echo ""
  exit 0
}

timestamp=$(date "+%Y-%m-%d %H:%M:%S")
echo "$timestamp - $0 $@"

# set default value
pantax_db="pantax_db"
create_db="False"
next_for_strain="False"
debug="False"
verbose="False"
short_reads="False"
long_reads="False"
pair_short_read="False"
short_read_best_alignment="False"
long_read_fast_alignment="False"
threads=64
gurobi_threads=1

species_level_flag="False"
strain_level_flag="False"
isfilter=0
save=0
species_abund_threshold=0.0001
unique_trio_nodes_fraction=0.3
unique_trio_nodes_count=0.45
min_cov=0
min_depth=0
sample=0

wd=$(pwd)
pantax_report=pantax_report.tsv

#Print help if no argument specified
if [[ "$1" == "" ]]; then
  print_help
fi

# get parameters
while [[ "$1" != "" ]]; do
    case "$1" in
    "--help" | "-h")
        print_help
        ;;
    "--version")
        echo "PanTax version v1.0.2"
        exit 0 
        ;;
    "--create")
        create_db="True"
        shift 1
        ;;
    "--vg")
        case "$2" in
        "")
        echo "Error: $1 expects an argument"
        exit 1
        ;;
        *)
        vg="$2"
        shift 2
        ;;
        esac
        ;;
    "-n" | "--next")
        next_for_strain="True"
        shift 1
        ;;
    "--debug")
        debug="True"
        shift 1
        ;;
    "--sample")
        sample=1
        shift 1
        ;;
    "-v" | "--verbose")
        verbose="True"
        shift 1
        ;;
    "-f" | "--genomesInformation")
        case "$2" in
        "")
        echo "Error: $1 expects an argument"
        exit 1
        ;;
        *)
        genomes_info="$2"
        shift 2
        ;;
        esac
        ;;
    "-db")
        case "$2" in
        "")
        echo "Error: $1 expects an argument"
        exit 1
        ;;
        *)
        pantax_db="$2"
        shift 2
        ;;
        esac
        ;;
    "-s" | "--short-read")
        short_reads="True"
        shift 1
        ;;
    "-l" | "--long-read")
        long_reads="True"
        shift 1
        ;;
    "--best")
        short_read_best_alignment="True"
        shift 1
        ;;
    "--fast")
        long_read_fast_alignment="True"
        shift 1
        ;;     
    "-r" | "--fastq-in")
        case "$2" in
        "")
        echo "Error: $1 expects an argument"
        exit 1
        ;;
        *)
        input_fq="$2"
        shift 2
        ;;
        esac
        ;;
    "-p" | "--paired")
        pair_short_read="True"
        shift 1
        ;;

    "--strain-level")
        strain_level_flag="True"
        shift 1
        ;;
    "--species-level")
        species_level_flag="True"
        shift 1
        ;;
    "--filter")
        isfilter=1
        shift 1
        ;;
    "-a")
        case "$2" in
        "")
        echo "Error: $1 expects an argument"
        exit 1
        ;;
        *)
        species_abund_threshold="$2"
        shift 2
        ;;
        esac
        ;;
    "-fr")
        case "$2" in
        "")
        echo "Error: $1 expects an argument"
        exit 1
        ;;
        *)
        unique_trio_nodes_fraction="$2"
        shift 2
        ;;
        esac
        ;;    
    "-fc")
        case "$2" in
        "")
        echo "Error: $1 expects an argument"
        exit 1
        ;;
        *)
        unique_trio_nodes_count="$2"
        shift 2
        ;;
        esac
        ;;     
    "--min_cov")
        case "$2" in
        "")
        echo "Error: $1 expects an argument"
        exit 1
        ;;
        *)
        min_cov="$2"
        shift 2
        ;;
        esac
        ;;
    "--min_depth")
        case "$2" in
        "")
        echo "Error: $1 expects an argument"
        exit 1
        ;;
        *)
        min_depth="$2"
        shift 2
        ;;
        esac
        ;;
    "-g" | "--save")
        save=1
        shift 1
        ;;                
    "-S" | "--classified-out")
        case "$2" in
        "")
        echo "Error: $1 expects an argument"
        exit 1
        ;;
        *)
        read_aln="$2".gaf
        shift 2
        ;;
        esac
        ;;                                                                           
    "-R" | "--report")
        case "$2" in
        "")
        echo "Error: $1 expects an argument"
        exit 1
        ;;
        *)
        pantax_report="$2".tsv
        shift 2
        ;;
        esac
        ;; 
    "-o" | "--output")
        case "$2" in
        "")
        echo "Error: $1 expects an argument"
        exit 1
        ;;
        *)
        pantax_output=$2
        shift 2
        ;;
        esac
        ;; 
    "-t" | "--threads")
        case "$2" in
        "")
        echo "Error: $1 expects an argument"
        exit 1
        ;;
        *)
        threads="$2"
        shift 2
        ;;
        esac
        ;;      
    "-gt")
        case "$2" in
        "")
        echo "Error: $1 expects an argument"
        exit 1
        ;;
        *)
        gurobi_threads="$2"
        shift 2
        ;;
        esac
        ;;                                                              
    --)
        shift
        break
        ;;
    *)
        echo "Error: invalid option \"$1\""
        exit 1
        ;;
    esac
done

if [ $genomes_info ] && [ -f $genomes_info ]; then
    genomes_info=$(readlink -f $genomes_info)
else
    echo "genomes information file does not exist!"
    exit 1
fi

if [ $create_db == "False" ]; then
    if [ $input_fq ] && [ -f $input_fq ]; then
        input_fq=$(readlink -f $input_fq)
    else
        echo "fastq file does not exist!"
        exit 1    
    fi

    # if [ $isfilter == 1 ]; then
    #     isfilter_flag=1
    # else
    #     isfilter_flag=0
    # fi
    isfilter_flag=1

    echo "Parameters settings:"
    echo "  threads: $threads"
    echo "Database creation:"
    echo "  genomes_info: $genomes_info"
    echo "  pantax_db: $pantax_db"
    echo "Index construction:"
    if [ $short_reads == "True" ]; then
        echo "  short_reads: $short_reads"
    elif [ $long_reads == "True" ]; then
        echo "  long_reads: $long_reads"
    else 
        echo "No read type!"
        exit 1
    fi
    echo "Read classification:"
    echo "  input_fq: $input_fq"
    echo "  strain_level_flag: $strain_level_flag"
    echo "  species_level_flag: $species_level_flag"
    if [ $strain_level_flag == "False" ] && [ $species_level_flag == "False" ]; then
        echo "No species or strain option specified. Please set --species-level or --strain-level."
        exit 1
    fi
fi

# some tools work in different directory when install with conda or from source.
if [[ $(which $0) == *conda* ]]; then
    conda_run_flag="True"
else 
    conda_run_flag="False"
fi
# set tools working path
script_path=$(readlink -f $0)
script_dir=$(dirname $script_path)
if [ $conda_run_flag == "True" ]; then
    # tools_dir=$script_dir/tools
    tools_dir=$script_dir
    fastix=$tools_dir/fastix
else
    tools_dir=$(dirname $script_dir)/tools
    fastix=$tools_dir/fastix/bin/fastix
fi
if [ $vg ]; then
    :
else
    vg=$tools_dir/vg
fi

# set pantax_db and tmp directory
if [ ! -d $pantax_db ]; then
    mkdir -p $pantax_db
# else
#     rm -rf $pantax_db
#     mkdir -p $pantax_db
fi
pantax_db=$(readlink -f $pantax_db)
# cd $pantax_db
if [ $next_for_strain == "False" ] && [ -d tmp ] && [ $debug == "False" ]; then
    rm -rf tmp
fi

mkdir -p tmp
tmp_dir=$(readlink -f tmp)
cd $tmp_dir
cleanup() {
    echo "$(date "+%Y-%m-%d %H:%M:%S") - PanTax encountered an exception while running and has deleted the tmp folder."
    echo "If you need to start checking not to delete the tmp directory, please add the --debug option."
    rm -rf $tmp_dir
}
if [ $debug == "False" ]; then
    trap cleanup ERR
fi

# ---------------------------- Building reference pangenome ----------------------------
if [ ! -f $pantax_db/reference_pangenome.gfa ]; then 
    new_pantax_db=$pantax_db
    pantax_db=$tmp_dir
    reconstruction_flag="True"
else
    reconstruction_flag="False"
fi

if [ $reconstruction_flag == "True" ]; then 
    echo "$(date "+%Y-%m-%d %H:%M:%S") - Building reference pangenome ..."
    # Prepare genomes information. Return pggb_species directory and species_eq1_genomes.txt
    # Species(in pggb_species directory) more than 2 genomes will be used to build pangenome firstly.
    python $script_dir/prepare_building.py $genomes_info $wd

    # build pangenome with pggb
    mkdir -p gfa_build
    cd gfa_build
    if [ -d $tmp_dir/pggb_species ]; then
        count=$(ls $tmp_dir/pggb_species | wc -l)
        if [ $count -ne 0 ]; then
            ls $tmp_dir/pggb_species/*.txt | while read f; do
                species_dir=$(basename $f)
                species_dir=${species_dir%.txt}
                if [ ! -d $species_dir ]; then
                    mkdir -p $species_dir
                else
                    continue
                fi
                while IFS= read genome; do
                    sample_genome=$(basename $genome | cut -f 1,2 -d '_')
                    # echo $genome
                    $fastix $genome -p "${sample_genome}#1#" | bgzip -@ $threads -c > ${species_dir}/${sample_genome}.fa.gz
                done < $f
                genomes_list=$(find $species_dir -name "*.fa.gz" -exec echo -n "{} " \;)
                num=$(ls $species_dir/*.fa.gz | wc -l)
                merge_file=${species_dir}/${species_dir}_merged.fa.gz
                zcat $genomes_list | bgzip -c -@ $threads > $merge_file
                samtools faidx $merge_file
                if [ $verbose == "True" ]; then
                    pggb -i $merge_file -o ${species_dir}/species${species_dir}_pggb -t $threads -p 90 -n $num -v
                elif [ $verbose == "False" ]; then
                    pggb -i $merge_file -o ${species_dir}/species${species_dir}_pggb -t $threads -p 90 -n $num -v > /dev/null 2>&1
                fi
            done
        fi
    fi
    cd ..

    # build variation graph for the species with one genomes
    python $script_dir/build_graph.py species_eq1_genomes.txt
    # rm -rf pggb_species species_eq1_genomes.txt
    # find gfa_build -type f -name "*.gfa" -exec bash -c 'input={}; name=$(basename $input); output=${name%%.*}.vg; vg convert -g $input -p > gfa_build/$output' \;
    find gfa_build -type f -name "*.gfa" -exec bash -c 'input="$1"; vg="$2"; name=$(basename "$input"); output=${name%%.*}.vg; "$vg" convert -g "$input" -p > gfa_build/"$output"' _ {} "$vg" \;
    vg_files=$(ls gfa_build/*.vg)
    $vg combine -p $vg_files > reference_pangenome.vg
    $vg convert -f reference_pangenome.vg > reference_pangenome.gfa
    rm reference_pangenome.vg
    python $script_dir/otu_range.py reference_pangenome.gfa $genomes_info --species-level 1 --strain-level 0
    # extract gfa files for strain abundance computing
    mkdir -p species_gfa
    find gfa_build -name "*gfa" -exec bash -c 'input={}; name=$(basename $input); output=${name%%_merge*}.gfa; mv $input species_gfa/$output' \;
    mv species_gfa reference_pangenome* species_range.txt $new_pantax_db
    pantax_db=$new_pantax_db
    echo "$(date "+%Y-%m-%d %H:%M:%S") - Building reference pangenome completely."
else
    echo "$(date "+%Y-%m-%d %H:%M:%S") - Reference_pangenome.gfa exists. Skipping."
fi

if [ $create_db == "True" ];then
    cd ..
    if [ $debug == "False" ]; then
        rm -rf tmp
    fi
    exit 0
fi

# ---------------------------- Reads alignment ----------------------------
# short reads alignment(the latest vg giraffe can be used for long reads)
if [[ ( $species_level_flag == "True" || $strain_level_flag == "True" ) && ( $short_reads == "True" || $long_read_fast_alignment == "True" ) ]]; then
    echo "$(date "+%Y-%m-%d %H:%M:%S") - Reads alignment with vg giraffe."    
    # this step produce three index files: reference_pangenome.giraffe.gbz, reference_pangenome.dist, reference_pangenome.min.
    # default mode(quick)
    if [ $reconstruction_flag == "True" ] || [ ! -e $pantax_db/reference_pangenome.min ]; then
        echo "$(date "+%Y-%m-%d %H:%M:%S") - Construct index...."
        if [ $short_read_best_alignment == "False" ] && [ ! -e $pantax_db/reference_pangenome.min ]; then
            # # these commands all can show progress with option -p
            $vg gbwt -g reference_pangenome.giraffe.gbz --gbz-format -G $pantax_db/reference_pangenome.gfa
            $vg index -j reference_pangenome.dist reference_pangenome.giraffe.gbz
            $vg minimizer -d reference_pangenome.dist -o reference_pangenome.min reference_pangenome.giraffe.gbz
        else
            $vg autoindex -p reference_pangenome -w giraffe -g $pantax_db/reference_pangenome.gfa -t $threads
        fi
        mv reference_pangenome* $pantax_db
    fi
    echo "$(date "+%Y-%m-%d %H:%M:%S") - vg giraffe mapping..."
    # $vg giraffe -Z reference_pangenome.giraffe.gbz -m reference_pangenome.min -d reference_pangenome.dist -i -f $input_fq -t $threads --named-coordinates > gfa_mapped.gam
    # $vg convert -a gfa_mapped.gam -j > gfa_mapped.json
    if [ $pair_short_read == "True" ] && [ ! -f gfa_mapped.gaf ]; then
        $vg giraffe -Z $pantax_db/reference_pangenome.giraffe.gbz -m $pantax_db/reference_pangenome.min -d $pantax_db/reference_pangenome.dist -i -f $input_fq -t $threads --named-coordinates -o gaf > gfa_mapped.gaf
    elif [ $pair_short_read == "False" ] && [ ! -f gfa_mapped.gaf ]; then
        $vg giraffe -Z $pantax_db/reference_pangenome.giraffe.gbz -m $pantax_db/reference_pangenome.min -d $pantax_db/reference_pangenome.dist -f $input_fq -t $threads --named-coordinates -o gaf > gfa_mapped.gaf
    fi
    if [ $strain_level_flag == "True" ] || [ $next_for_strain == "True" ]; then
        if [ ! -f gfa_mapped.json ]; then
            $vg giraffe -Z $pantax_db/reference_pangenome.giraffe.gbz -m $pantax_db/reference_pangenome.min -d $pantax_db/reference_pangenome.dist -i -f $input_fq -t $threads --named-coordinates -o json > gfa_mapped.json
        else
            echo "gfa_mapped.json file exists. skipping alignment."
        fi
    fi
fi

# long reads alignment
if [ $species_level_flag == "True" ] && [ $long_reads == "True" ] && [ $long_read_fast_alignment == "False" ] && [ ! -f gfa_mapped.gaf ]; then
    echo "$(date "+%Y-%m-%d %H:%M:%S") - Reads alignment with Graphaligner..."
    if [ $strain_level_flag == "True" ] || [ $next_for_strain == "True" ]; then
        GraphAligner -g $pantax_db/reference_pangenome.gfa -f $input_fq -a gfa_mapped.gaf -a gfa_mapped.json -x vg -t $threads
        python $script_dir/gaf_filter.py -i gfa_mapped.gaf
        python $script_dir/gaf_filter.py -i gfa_mapped_filtered.gaf -j gfa_mapped.json -s $pantax_db/species_range.txt
        # python $script_dir/gaf_filter2.py -i gfa_mapped.gaf
        # awk 'NR==FNR{lines[$1]; next} FNR in lines' gfa_mapped_filtered_line_numbers.txt gfa_mapped.json > gfa_mapped_filtered.json
        # cp gfa_mapped.gaf gfa_mapped_old.gaf
        # cp gfa_mapped.json gfa_mapped_old.json
        mv gfa_mapped_filtered.gaf gfa_mapped.gaf
        mv gfa_mapped_filtered.json gfa_mapped.json
    else
        GraphAligner -g $pantax_db/reference_pangenome.gfa -f $input_fq -a gfa_mapped.gaf -x vg -t $threads
        python $script_dir/gaf_filter.py -i gfa_mapped.gaf
        mv gfa_mapped_filtered.gaf gfa_mapped.gaf
    fi
fi

# ---------------------------- Reads classification(binning) ----------------------------
if [ $species_level_flag == "True" ] && [ -f "gfa_mapped.gaf" ] && [ -f $pantax_db/species_range.txt ]; then
    echo "$(date "+%Y-%m-%d %H:%M:%S") - Read classification..."
    # python $script_dir/read_classification2.py species_range.txt gfa_mapped.json
    python $script_dir/read_classification.py -s $pantax_db/species_range.txt -m gfa_mapped.gaf
fi

# ---------------------------- species level binning and profiling ----------------------------
if [ $species_level_flag == "True" ]; then
    echo "$(date "+%Y-%m-%d %H:%M:%S") - Species abundance estimation..."
    if [ $short_reads == "True" ]; then
        python $script_dir/species_abundance_cal.py $genomes_info reads_classification.csv short -ft $isfilter_flag $wd
    elif [ $long_reads == "True" ]; then
        python $script_dir/species_abundance_cal.py $genomes_info reads_classification.csv long -ft $isfilter_flag $wd
    fi
fi 

# ---------------------------- strain level binning and profiling ----------------------------
if [ $strain_level_flag == "True" ]; then
    echo "$(date "+%Y-%m-%d %H:%M:%S") - Strain abundance estimation..."
    if [ $verbose == "True" ]; then
        python $script_dir/strain_abundance_cal.py -a $species_abund_threshold -fr $unique_trio_nodes_fraction -fc $unique_trio_nodes_count -c $min_cov -d $min_depth -t $threads -gt $gurobi_threads -s $save --sample $sample -v $pantax_db $genomes_info reads_classification.csv gfa_mapped.json $pantax_db/species_range.txt species_abundance.txt 
    else
        python $script_dir/strain_abundance_cal.py -a $species_abund_threshold -fr $unique_trio_nodes_fraction -fc $unique_trio_nodes_count -c $min_cov -d $min_depth -t $threads -gt $gurobi_threads -s $save --sample $sample $pantax_db $genomes_info reads_classification.csv gfa_mapped.json $pantax_db/species_range.txt species_abundance.txt 
    fi
    if [ $save == 1 ]; then
        if [ $reconstruction_flag == "False" ]; then
            mv species_graph_info $pantax_db
        else
            mv species_graph_info $new_pantax_db
        fi
    fi
fi

# move and rename files
cd ..
if [ $species_level_flag == "True" ]; then
    cp $tmp_dir/species_abundance.txt $wd
    if [ $pantax_output ]; then
        specie_abund_file=${pantax_output}_species_abundance.txt
        mv $wd/species_abundance.txt $specie_abund_file        
    fi
fi
if [ $strain_level_flag == "True" ]; then
    cp $tmp_dir/strain_abundance.txt $wd
    if [ $pantax_output ]; then
        strain_abund_file=${pantax_output}_strain_abundance.txt
        mv $wd/strain_abundance.txt $strain_abund_file
    fi
fi

# if next_for_strain is true, we will save tmp files for strain level profiling.
if [[ ( $strain_level_flag == "True" && $next_for_strain == "True" ) || ( $species_level_flag == "True" && $next_for_strain == "False" ) ]]; then
    if [ $read_aln ]; then
        mv $tmp_dir/gfa_mapped.gaf $wd
        mv $wd/gfa_mapped.gaf $read_aln
    fi

    cp $tmp_dir/reads_classification.csv $wd
    mv $wd/reads_classification.csv $pantax_report
    if [ $debug == "False" ]; then
        mv $tmp_dir/reads_classification.csv $wd
        mv $wd/reads_classification.csv $pantax_report
        rm -rf tmp
    fi
fi
echo "$(date "+%Y-%m-%d %H:%M:%S") - PanTax Done."